package main

const refTemplate = `---
name: sage-wiki
description: Reference skill for sage-wiki — local-first knowledge graph with MCP server, REST API, compiled wiki, and Obsidian-compatible output.
version: "0.1.0"
generated: skillgen — do not hand-edit
---

# sage-wiki

Local-first knowledge graph that compiles documents into an interlinked, human-readable wiki with provenance. Exposes {{.ToolCount}} MCP tools over stdio/SSE and a versioned REST API under ` + "`/v1/`" + `. Output is Obsidian-compatible markdown.

## How to connect

**MCP (primary):** The server runs as a subprocess over stdio, or over SSE/HTTP:
` + "```json" + `
{
  "mcpServers": {
    "sage-wiki": {
      "command": "sage-wiki",
      "args": ["serve", "--transport", "stdio", "--project", "/path/to/wiki"]
    }
  }
}
` + "```" + `

**REST (` + "`/v1/`" + `):** When the server is running with ` + "`--ui`" + `, the REST facade is at ` + "`/v1/`" + `. Auth is Bearer-token (same as ` + "`SAGE_WIKI_TOKEN`" + `); loopback is zero-config. All errors use a fixed ` + "`{error: {code, message, details}}`" + ` envelope.

## The {{.ToolCount}} MCP Tools

{{range .Tools}}
### ` + "`{{.Name}}`" + ` ({{.Kind}})
{{.Description}}
- **REST:** {{.REST}}
{{if .Args}}| Argument | Type | Required | Default |
|----------|------|----------|---------|
{{range .Args}}| ` + "`{{.Name}}`" + ` | {{.Type}} | {{if .Required}}yes{{else}}no{{end}} | {{.Default}} |
{{end}}
{{end}}
{{end}}

## Error Codes

Branch on ` + "`code`" + `, never on ` + "`message`" + `:

| Code | HTTP | When |
|------|------|------|
{{range .ErrorCodes}}| ` + "`{{.Code}}`" + ` | {{.HTTP}} | {{.When}} |
{{end}}

## Opt-In Features

All opt-in flags live under ` + "`config.yaml` → `ontology`" + `:

| Flag | Default | Unlocks |
|------|---------|---------|
{{range .OptInFlags}}| ` + "`{{.Flag}}`" + ` | {{.Default}} | {{.Unlocks}} |
{{end}}

## Tiers

Sources are assigned a tier determining compile depth:

| Tier | Label | What Happens |
|------|-------|--------------|
{{range .Tiers}}| {{.Tier}} | {{.Label}} | {{.Desc}} |
{{end}}

**There is no Tier 2.** Tiers go 0 → 1 → 3.

## Important Correctness Points

1. Tiers are **0 / 1 / 3** — there is no Tier 2. Documents and tooltips that claim a Tier 2 are wrong.
2. ` + "`ontology.temporal.enabled`" + ` defaults **true** (per code). ` + "`ontology.triples`" + `, ` + "`ontology.resolve`" + `, and ` + "`ontology.communities`" + ` default **false**.
3. ` + "`as_of`" + ` requires ` + "`ontology.temporal.enabled`" + `; ` + "`mode=global`" + ` requires ` + "`ontology.communities.enabled`" + `.
4. ` + "`compile`" + ` and ` + "`lint`" + ` are **job submissions** — they return ` + "`202 Accepted`" + ` with a ` + "`job_id`" + `, not a blocking result. Poll ` + "`GET /v1/jobs/{id}`" + ` for status.
5. Evidence spans (` + "`provenance`" + `) quote the **compiled summary**, not the source document. The summary is the distilled, LLM-processed form.

## Install

` + "```bash" + `
# MCP (stdio — primary integration path)
sage-wiki serve --project /path/to/wiki

# REST (with Web UI)
sage-wiki serve --ui --project /path/to/wiki

# Agent skill installation
npx skills add https://github.com/xoai/sage-wiki --skill sage-wiki
` + "```" + `

> **Pre-1.0 notice:** Every surface here is experimental. Tool semantics, argument names, and REST routes may change between versions. Pin the version you depend on.

Generated by tools/skillgen — {{.ToolCount}} tools in registry.
`

const pipeTemplate = `---
name: sage-wiki-integrate
description: Pipeline skill that wires sage-wiki into an existing project — detects language, installs the client, runs a smoke test, and reports.
version: "0.1.0"
generated: skillgen — do not hand-edit
---

# sage-wiki-integrate

Wires sage-wiki into an existing repository so the coding assistant can store and retrieve knowledge with provenance. Test-first — every step is verified before proceeding.

## Step 1: Detect language

Check the project root for language markers:

| Marker | Language | Integration path |
|--------|----------|-----------------|
| ` + "`pyproject.toml`" + ` | Python | ` + "`pip install sagewiki`" + ` (Python client, P4-3) |
| ` + "`package.json`" + ` | TypeScript / JavaScript | ` + "`npm install sagewiki`" + ` (TypeScript client, P4-4) |
| Neither | Any | MCP stdio config |

## Step 2: Choose integration path

### Python (` + "`pyproject.toml`" + ` found)

` + "```bash" + `
pip install sagewiki
` + "```" + `

` + "```python" + `
from sagewiki import Client

client = Client(base_url="http://localhost:3333/v1")
# If token-protected:
# client = Client(base_url="http://localhost:3333/v1", token="s3cret")
` + "```" + `

### TypeScript (` + "`package.json`" + ` found)

` + "```bash" + `
npm install sagewiki
` + "```" + `

` + "```typescript" + `
import { Client } from "sagewiki";

const client = new Client({ baseUrl: "http://localhost:3333/v1" });
// If token-protected:
// const client = new Client({ baseUrl: "http://localhost:3333/v1", token: "s3cret" });
` + "```" + `

### Neither (MCP stdio)

Add to the project's MCP config:

` + "```json" + `
{
  "mcpServers": {
    "sage-wiki": {
      "command": "sage-wiki",
      "args": ["serve", "--transport", "stdio", "--project", "."]
    }
  }
}
` + "```" + `

## Step 3: Write a smoke test

Store a fact, search for it, verify it comes back:

**Python smoke test:**
` + "```python" + `
# Store a fact via capture
resp = client.capture(content="smoke-test: sage-wiki integration works at {now}")
assert resp.status == "ok"

# Search for it
results = client.search(query="smoke-test sage-wiki integration")
assert len(results) > 0, "smoke test failed: no results for stored fact"
print("PASS: smoke test")
` + "```" + `

**TypeScript smoke test:**
` + "```typescript" + `
const resp = await client.capture({ content: "smoke-test: sage-wiki integration works" });
const results = await client.search({ query: "smoke-test sage-wiki integration" });
console.assert(results.length > 0, "smoke test failed");
console.log("PASS: smoke test");
` + "```" + `

**MCP smoke test** (call ` + "`wiki_capture`" + ` then ` + "`wiki_search`" + ` via your MCP client):

` + "```" + `
Tool: wiki_capture
Args: { content: "smoke-test: sage-wiki integration works at {timestamp}" }
Expected: confirmation text, no error

Tool: wiki_search
Args: { query: "smoke-test sage-wiki integration" }
Expected: at least one result, no error
` + "```" + `

## Step 4: Run the smoke test

Execute the chosen smoke test. If it fails:
- Check the server is running (` + "`sage-wiki serve --ui`" + `)
- Verify the token is correct (if auth is enabled)
- Check the server logs for errors

## Step 5: Report

After a successful smoke test, confirm:

- sage-wiki is connected and reachable
- The chosen integration path works
- Store → search → verify cycle completes

Then refer to the ` + "`sage-wiki`" + ` reference skill for the full tool catalog, error codes, and opt-in features.

> **Pre-1.0 notice:** Every surface here is experimental. Tool semantics, argument names, and REST routes may change between versions. Pin the version you depend on.

Generated by tools/skillgen — reference skill covers {{.ToolCount}} tools.
`
